{{- $secretName := printf "%s-regcred" .Release.Name }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.dockerCredentials | b64enc }}
