apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName | default .Chart.Name }}
  labels:
    app: {{ .Values.appLabel | default .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8080
    nodePort: {{ .Values.service.nodePort }}
  selector:
    app: {{ .Values.appLabel | default .Chart.Name }}
